### PR TITLE
Added .get, .post, .put, .delete and .getUserId to the Client

### PR DESCRIPTION
**Pull request by FishingHacks**
Here u go :>

Added:
- .get({endpoint, header, params}): Makes a get request
- .put({endpoint, header, params}): Makes a put request
- .post({endpoint, header, params}): Makes a post request
- .delete({endpoint, header, params}): Makes a delete request
- .getUserId(username): Gets the user id

.get, .put, .post and .delete are really convenience functions, that promsie parameter security

# Warning
I didn't test this code, as I couldn't figure out how to obtain a secret and token, thus someone needs to test this

### CODE REVIEW

**Comment by FishingHacks** [comment]
#3

**Comment by FishingHacks** [comment]
Example code:
```js
await Client.get({
  endpoint: endpoints.CHANNEL_POINTS.GET_CUSTOM_REWARD_REDEMPTION,
  broadcaster_id: await Client.getUserId("name")
})
```

**Comment by FishingHacks** [comment]
@RedCrafter07 :grin:

**Comment by RedCrafter07** [comment]
You may test it before I merge 😅

**Comment by FishingHacks** [comment]
i tested it, but it said, no token or secret to be found cuz i don't have one, but the url seemed right. Maybe implement Testing actions, ms surely won't do bad things with ur twitch tokens

**Pull request closed without merging**
